stages:
- name: Build
  steps:
  - runScriptConfig:
      image: php:7.3-apache
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: if-site:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yml