version: '3'

services:
  insider_framework_site:
    image: php:7.3-apache
    # ports:
    #    - 80:80
    expose:
      - "80"
    build:
      dockerfile: ./insider_framework-site.dockerfile
      context: .
    stdin_open: true
    tty: true
    volumes:
      - "../:/var/www/insiderframework"
    restart: always

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
                         
      # Port: 443 to 80
      - "traefik.app.frontend.rule=Host:www.insiderframework.com.br,insiderframework.com.br,www.insiderframework.com,insiderframework.com"
      - "traefik.app.backend=insiderframework_site"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=https"

      # Port: 80 to 80
      #- "traefik.app.frontend.rule=Host:www.whoami.local"
      #- "traefik.app.backend=whoami"
      #- "traefik.port=80"
      #- "traefik.frontend.entryPoints=http"
    networks:
      - iti_internal

networks:
  web:
    external: true
  iti_internal:
    external: true
