version: '3'

services:
    insider_framework:
        image: php:7.3-apache
        ports:
            - 80:80
        expose:
            - "80"

        build:
            dockerfile: ./insider_framework.dockerfile
            context: .
        stdin_open: true
        tty: true
        networks:
            - insider_network
        volumes:
            - "../:/var/www/insiderframework"
        restart: always
        
    mariadb:
        image: mariadb:latest
        ports:
            - 3306:3306
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: test
        networks:
            - insider_network
        restart: on-failure
        volumes:
            - ${PWD}/mariadb:/var/lib/mysql
        networks:
            insider_network:
                ipv4_address: 172.19.0.3

networks:
    insider_network:
        driver: bridge
